INSERT INTO UniDB.dbo.Persons (AddressID, ContactInformationID, Firstname, Lastname)
VALUES 
(5, 5, 'Mary', 'Ball'),
(8, 6, 'Morgan', 'Hernandez'),
(2, 15, 'Liva', 'Carlsen'),
(6, 1, 'Sam', 'Askew'),
(12, 20, 'Alex', 'Charlton'),
(1, 8, 'Patrick', 'Johnson'),
(7, 18, 'Frederikke', 'Vestergaard'),
(3, 12, 'Amanda', 'Watson'),
(4, 17, 'Deborah', 'Martinez'),
(3, 13, 'Kenneth', 'Wilson'),
(9, 4, 'Jenny', 'Wright'),
(10, 7, 'Esad', 'Raats'),
(6, 19, 'Katherine', 'Smelser'),
(10, 9, 'Danila', 'Zelm'),
(7, 16, 'Emma', 'Iversen'),
(11, 22, 'Dewey', 'Robinson'),
(13, 14, 'Georgetta', 'Sayre'),
(9, 10, 'Claude', 'Miller'),
(13, 2, 'Barbara', 'Nguyen'),
(11, 3, 'Milda', 'Wolf'),
(12, 21, 'Danielle', 'Johnston'),
(3, 11, 'Leon', 'Plyler');